# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=py34
  - TOXENV=py27
  - TOXENV=flake8
  - TOXENV=isort

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox codecov

# command to run tests, e.g. python setup.py test
script:
  - make test-all

after_success:
  - codecov
